[package]
name = "dlnaproxy"
version = "0.1.0"
authors = ["Nic0w"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true

[dependencies]
httparse = ""
timer = ""
chrono = ""
clap = ""
nix = ""
fern = ""

[dependencies.log]
version = ""
features = ["std"]

[dependencies.reqwest]
default-features = false
version = ""
features = ["blocking"]

[dependencies.serde]
version = ""
features = ["derive"]

[dependencies.quick-xml]
version = ""
features = ["serialize"]
