[package]
name = "dlnaproxy"
version = "0.2.4"
authors = ["Nic0w"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true

[dependencies]
httparse = "1.6.0"
timer = { git = "https://github.com/Yoric/timer.rs", branch = "master" }
chrono = "0.4.19"
clap = { version = "3.1.8", features = ["derive"] }
nix = "0.23.1"
fern = "0.6.0"
ctrlc = "3.2.1"
toml = "0.5.8"

[dependencies.log]
version = "0.4.16"
features = ["std"]

[dependencies.reqwest]
default-features = false
version = "0.11.10"
features = ["blocking"]

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dependencies.quick-xml]
version = "0.22.0"
features = ["serialize"]
