[package]
name = "dlnaproxy"
version = "0.2.3"
authors = ["Nic0w"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true

[dependencies]
httparse = "*"
timer = { git = "https://github.com/Yoric/timer.rs", branch = "master" }
chrono = "*"
clap = "*"
nix = "*"
fern = "*"
ctrlc = "*"
toml = "*"

[dependencies.log]
version = "*"
features = ["std"]

[dependencies.reqwest]
default-features = false
version = "*"
features = ["blocking"]

[dependencies.serde]
version = "*"
features = ["derive"]

[dependencies.quick-xml]
version = "*"
features = ["serialize"]
